"""Tests for bin/ucw-pr-meta.py — the PR title/body generator used by
/ucw ship at auto-mode level 4."""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
BIN = REPO_ROOT / "bin" / "ucw-pr-meta.py"


def _run(args: list[str], cwd: Path) -> tuple[int, str, str]:
    cp = subprocess.run(
        [sys.executable, str(BIN), *args],
        cwd=cwd, capture_output=True, text=True, timeout=10,
    )
    return cp.returncode, cp.stdout, cp.stderr


def _git(args: list[str], cwd: Path, *, env: dict | None = None) -> None:
    e = os.environ.copy()
    e.update({
        "GIT_AUTHOR_NAME": "Test", "GIT_AUTHOR_EMAIL": "t@e.com",
        "GIT_COMMITTER_NAME": "Test", "GIT_COMMITTER_EMAIL": "t@e.com",
    })
    if env:
        e.update(env)
    # Disable signing — sandboxed test envs don't have the signing key
    subprocess.run(
        ["git", "-c", "commit.gpgsign=false", "-c", "tag.gpgsign=false", *args],
        cwd=cwd, check=True, env=e, capture_output=True, text=True,
    )


@pytest.fixture
def repo(tmp_path):
    """Init a real git repo so the helper can run git commands against it."""
    _git(["init", "-b", "main"], cwd=tmp_path)
    (tmp_path / "README.md").write_text("# Test\n")
    _git(["add", "README.md"], cwd=tmp_path)
    _git(["commit", "-m", "initial"], cwd=tmp_path)
    return tmp_path


@pytest.fixture
def feature_branch(repo):
    """A branch with one feature commit ahead of main."""
    _git(["checkout", "-b", "feature/healthz"], cwd=repo)
    (repo / "app.py").write_text("def healthz(): return 'ok'\n")
    _git(["add", "app.py"], cwd=repo)
    _git(["commit", "-m", "Add /healthz endpoint\n\nSimple liveness probe for the demo Flask app."],
         cwd=repo)
    return repo


# ---- happy path ------------------------------------------------------------

def test_generates_title_from_commit_subject(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    assert rc == 0
    meta = json.loads(out)
    assert meta["title"] == "Add /healthz endpoint"


def test_includes_body_paragraphs(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    meta = json.loads(out)
    assert "Simple liveness probe" in meta["body"]


def test_diff_stat_lists_changed_files(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    meta = json.loads(out)
    assert "app.py" in meta["diff_stat"]


def test_commits_ahead_count_is_correct(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    meta = json.loads(out)
    assert meta["commits_ahead"] == 1


def test_head_branch_is_current_branch(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    meta = json.loads(out)
    assert meta["head_branch"] == "feature/healthz"


def test_base_branch_default_is_main(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    meta = json.loads(out)
    assert meta["base_branch"] == "main"


def test_base_branch_override(feature_branch):
    _git(["branch", "develop"], cwd=feature_branch)
    rc, out, _ = _run(["--base", "develop"], cwd=feature_branch)
    meta = json.loads(out)
    assert meta["base_branch"] == "develop"


def test_body_has_test_plan_section(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    meta = json.loads(out)
    assert "## Test plan" in meta["body"]
    assert "- [ ]" in meta["body"]


def test_body_has_auto_generated_footer(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    meta = json.loads(out)
    assert "Auto-generated by UCW" in meta["body"]
    assert "/ucw auto off" in meta["body"]


def test_body_has_changes_section_with_diff_stat(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    meta = json.loads(out)
    assert "## Changes" in meta["body"]
    assert "app.py" in meta["body"]


# ---- edge cases ------------------------------------------------------------

def test_long_subject_is_truncated(repo):
    _git(["checkout", "-b", "feature/long"], cwd=repo)
    (repo / "f.py").write_text("x")
    _git(["add", "f.py"], cwd=repo)
    subject = "Add a very long feature with lots of description and many additional words that exceed 70 chars"
    _git(["commit", "-m", subject], cwd=repo)
    rc, out, _ = _run([], cwd=repo)
    meta = json.loads(out)
    assert len(meta["title"]) <= 70
    # And the cut should be word-boundary aware (no mid-word truncation)
    assert not meta["title"].endswith(" ")


def test_subject_under_70_chars_is_unchanged(feature_branch):
    rc, out, _ = _run([], cwd=feature_branch)
    meta = json.loads(out)
    assert meta["title"] == "Add /healthz endpoint"


def test_missing_body_falls_back_to_italic_subject(repo):
    _git(["checkout", "-b", "feature/noBody"], cwd=repo)
    (repo / "x.py").write_text("y")
    _git(["add", "x.py"], cwd=repo)
    _git(["commit", "-m", "Subject only, no body"], cwd=repo)
    rc, out, _ = _run([], cwd=repo)
    meta = json.loads(out)
    assert "_Subject only, no body_" in meta["body"]


def test_no_commits_ahead_returns_warning_and_exit_2(repo):
    """On the base branch itself, head_branch == base → no PR makes sense."""
    _git(["checkout", "-b", "side"], cwd=repo)
    # No new commits — still on the same SHA as main
    rc, out, _ = _run([], cwd=repo)
    meta = json.loads(out)
    assert meta["commits_ahead"] == 0
    assert "warning" in meta
    assert rc == 2  # signals "nothing to PR" to ship caller


def test_missing_base_branch_does_not_crash(feature_branch):
    """If base ref doesn't exist (fresh clone, weird config), we shouldn't
    explode — just note it in the diff_stat field."""
    rc, out, _ = _run(["--base", "nonexistent"], cwd=feature_branch)
    meta = json.loads(out)
    assert "not found" in meta["diff_stat"]
    assert meta["commits_ahead"] == 0


def test_detached_head_falls_back_to_short_sha(repo):
    _git(["checkout", "-b", "tmp"], cwd=repo)
    (repo / "a"). write_text("a")
    _git(["add", "a"], cwd=repo)
    _git(["commit", "-m", "tmp commit"], cwd=repo)
    sha = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip()
    _git(["checkout", sha], cwd=repo)  # detached
    rc, out, _ = _run([], cwd=repo)
    meta = json.loads(out)
    assert meta["head_branch"] == sha[:12], \
        f"detached HEAD should fall back to short sha, got {meta['head_branch']!r}"


def test_not_a_git_repo_returns_error(tmp_path):
    rc, out, err = _run([], cwd=tmp_path)
    assert rc == 1
    # Error printed to stderr as JSON
    err_data = json.loads(err)
    assert err_data["error"] == "git command failed"


# ---- base ref option-injection guard ---------------------------------------

@pytest.mark.parametrize("bad_base", [
    "--output=/tmp/pwned",   # git diff --output writes to an arbitrary file
    "-f",
    "--upload-pack=touch x",
])
def test_base_starting_with_dash_is_rejected(feature_branch, bad_base):
    """A `--base` that could be parsed as a git flag must be refused, not
    interpolated into a refspec (option-injection guard). The `--base=<v>`
    form is used so argparse passes the dash value through to our validator
    rather than rejecting it as a stray option itself."""
    rc, _out, err = _run([f"--base={bad_base}"], cwd=feature_branch)
    assert rc == 1
    err_data = json.loads(err)
    assert err_data["error"] == "invalid base ref"
    # The dangerous value never reached git as a flag.
    assert not (feature_branch / "tmp" / "pwned").exists()
